### ISSUE TITLE
Does fixed even replace if null?

### ISSUE THREAD

**Issue by Mat-Moo** [ppomes/myanon#20] opened 2023-01-09 15:14 UTC
Got some areas where I have to use fixed to set the value, but looks like if this was null it still replaces it with fixed (I believe?) text hash only seems to replace when it's not null, so maybe need a fixed leave null flag / option? fixed "1234567" true (not default, don't replace null)

**Comment by ppomes** [comment] 2023-01-09 16:08
Good catch, I think this is a bug, since '*hash' do not replace NULL values, 'fixed' should do the same.

**Comment by ppomes** [comment] 2023-01-11 19:52
Hi! 

Happy new year! After analyzing, I was wrong on my previous comment. 'fixed' does not anonymize NULL values. I updated the "null-example" test case to show this.

Could you provide a test case for which this is not working as it should?

Thanks!
Pierre

**Comment by Mat-Moo** [comment] 2023-01-14 11:20
I'll have to run another test, maybe I jumped to conclusions

**Comment by ppomes** [comment] 2023-04-23 18:52
Hi ! Did you have any opportunity to test again?

**Comment by ppomes** [comment] 2023-04-27 20:53
For now, I close this issue, but do not hesitate to re-open it if you can reproduce the problem!

**Closed by ppomes** 2023-04-27 20:53 UTC
Labels: help wanted, question
